#!/bin/bash -
# run sailsys with the default config file

pushd /sailsys

# make sailsys executable if required
if [ ! -x sailsys ]
then
  echo fix permisions at sailsys
  chmod a+x sailsys
fi

# set capabilities to use the scheduler feature
sudo setcap 'cap_sys_rawio,cap_net_admin,cap_sys_time,cap_net_bind_service,cap_sys_nice=+eip' /sailsys/sailsys

# enable core dumps
# ulimit -c unlimited

title bravo_systems >> /sailsys/data/error.log
./sailsys -v 
#./sailsys -v 
# ready for debugging
#
#cd cfg;gdbserver host:2345 sailsys -v
#
popd
#reset

